=== NorthArrowResearch/Program/Program/XSD/V1/Program.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Program" type="ProgramType"/>

  <xs:complexType name="ProgramType">
    <xs:sequence>
      <xs:element type="MetaDataType" name="MetaData" maxOccurs="unbounded" minOccurs="0"/>
      <xs:choice>
        <xs:element type="BucketType" name="Level" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element type="BucketType" name="Container" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element type="ProductType" name="Product" maxOccurs="unbounded" minOccurs="0"/>
      </xs:choice>
    </xs:sequence>

    <xs:attribute type="xs:string" name="name"/>
  </xs:complexType>

  <xs:complexType name="BucketType">
    <xs:sequence>
      <xs:element type="BucketType" name="Level" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="BucketType" name="Container" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="ProductType" name="Product" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="ProductType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:string" name="folder" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="MetaType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="MetaDataType">
    <xs:sequence>
      <xs:element type="MetaType" name="Meta" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>


</xs:schema>

=== NorthArrowResearch/Program/Program/Riverscapes.xml
<?xml version="1.0" encoding="utf-8"?>
<Program name="Riverscapes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="Program.xsd">
  <MetaData>
    <Meta name="s3bucket">riverscapesdata</Meta>
  </MetaData>
  <Level name="Region">
    <Level name="Watershed">
        <Container name="Watershed">
          <Product name="GRTS Rollup" id="GRTS" folder="grts"/>
          <Product name="Context Layers" id="context" folder="context_layers"/>
        </Container>
        <Container name="Network">
          <Product name="BRAT Models" id="BRAT" folder="brat"/>
            <Product name="WRAT" id="WRAT" folder="wrat"/>
            <Product name="Matt Imputation Crap" id="MIC" folder="matt_impute"/>
            <Product name="GPP" id="GPP" folder="gpp"/>
            <Product name="Capacity" id="capacity" folder="capacity"/>
            <Product name="River Styles" id="RSTYLES" folder="riverstyles"/>
        </Container>
        <Container name="Sites">
          <Level name="Site">
            <Level name="Visit">
              <Level name="Year">
                <Level name="Flow">
                  <Product name="FHM" id="FHM" folder="FHM"/>
                  <Product name="GUT" id="GUT" folder="GUT"/>
                  <Product name="GCD" id="GCD" folder="GCD"/>
                </Level>
                <Container name="Topography">
                  <Product name="DEM" id="DEM" folder="DEM"/>
                </Container>
              </Level>
            </Level>
          </Level>
        </Container>
    </Level>
  </Level>
</Program>
